import Head from "next/head";
import HomePage from "./home";
import MainSection from "@/components/mainsection/MainSection";
import Footer from "@/components/footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mobius</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HomePage/>
        <MainSection/>
        <Footer/>

 
      </div>
    </>
  );
}
